import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-photo-album',
  standalone: true,
  imports: [
    CommonModule
  ],
  templateUrl: './photo-album.component.html',
  styleUrl: './photo-album.component.css'
})
export class PhotoAlbumComponent {
  memories = [
    { subtitle: 'Felicidade', description: 'Um momento inesquecível', image: 'assets/img/album/1.jpg', flipped: false },
    { subtitle: 'Amor', description: 'Recordações especiais', image: 'assets/img/album/2.jpg', flipped: false },
    { subtitle: 'Paz', description: 'Uma alegria contagiante', image: 'assets/img/album/3.jpg', flipped: false },
    { subtitle: 'Alegria', description: 'Celebrando a vida', image: 'assets/img/album/4.jpg', flipped: false },
    { subtitle: 'Esperança', description: 'Um dia para lembrar', image: 'assets/img/album/5.jpg', flipped: false },
    { subtitle: 'Aventura', description: 'Experiência única', image: 'assets/img/album/6.jpg', flipped: false },
    { subtitle: 'Diversão', description: 'Sorrisos compartilhados', image: 'assets/img/album/7.jpg', flipped: false },
    { subtitle: 'Tradição', description: 'Sentimentos profundos', image: 'assets/img/album/8.jpg', flipped: false },
    { subtitle: 'Sonho', description: 'Histórias contadas', image: 'assets/img/album/9.jpg', flipped: false },
    { subtitle: 'Celebração', description: 'Memórias eternas', image: 'assets/img/album/10.jpg', flipped: false },
    { subtitle: 'Conquista', description: 'Um dia perfeito', image: 'assets/img/album/11.jpg', flipped: false },
    { subtitle: 'Amizade', description: 'Uma lembrança querida', image: 'assets/img/album/12.jpg', flipped: false },
    { subtitle: 'Gratidão', description: 'Paz interior', image: 'assets/img/album/13.jpg', flipped: false },
    { subtitle: 'Inspiração', description: 'Momentos felizes', image: 'assets/img/album/14.jpg', flipped: false },
    { subtitle: 'Riso', description: 'Conexões verdadeiras', image: 'assets/img/album/15.jpg', flipped: false },
    { subtitle: 'Luz', description: 'A magia do momento', image: 'assets/img/album/16.jpg', flipped: false },
    { subtitle: 'Harmonia', description: 'Uma nova aventura', image: 'assets/img/album/17.jpg', flipped: false },
    { subtitle: 'Encanto', description: 'Celebração de conquistas', image: 'assets/img/album/18.jpg', flipped: false },
    { subtitle: 'Magia', description: 'Gratidão e alegria', image: 'assets/img/album/19.jpg', flipped: false },
    { subtitle: 'Calma', description: 'Um sonho realizado', image: 'assets/img/album/20.jpg', flipped: false },
    { subtitle: 'Orgulho', description: 'Beleza e harmonia', image: 'assets/img/album/21.jpg', flipped: false },
    { subtitle: 'Saudade', description: 'Reflexões sobre a vida', image: 'assets/img/album/22.jpg', flipped: false },
    { subtitle: 'Sorrisos', description: 'Momentos de calma', image: 'assets/img/album/23.jpg', flipped: false },
    { subtitle: 'Unidade', description: 'Carinho e afeto', image: 'assets/img/album/24.jpg', flipped: false },
    { subtitle: 'Beleza', description: 'Um sorriso genuíno', image: 'assets/img/album/25.jpg', flipped: false },
    { subtitle: 'Sorte', description: 'Lembranças que aquecem o coração', image: 'assets/img/album/26.jpg', flipped: false },
    { subtitle: 'Coragem', description: 'Felicidade pura', image: 'assets/img/album/27.jpg', flipped: false },
    { subtitle: 'Sucesso', description: 'Superando desafios', image: 'assets/img/album/28.jpg', flipped: false },
    { subtitle: 'Momento', description: 'Emoções intensas', image: 'assets/img/album/29.jpg', flipped: false },
    { subtitle: 'Apreciar', description: 'Momentos de reflexão', image: 'assets/img/album/30.jpg', flipped: false },
    { subtitle: 'Carinho', description: 'Conquista pessoal', image: 'assets/img/album/31.jpg', flipped: false },
    { subtitle: 'Sorte', description: 'Alegria em cada detalhe', image: 'assets/img/album/32.jpg', flipped: false },
    { subtitle: 'Reflexão', description: 'Sentimento de realização', image: 'assets/img/album/33.jpg', flipped: false },
    { subtitle: 'Companheirismo', description: 'Apreciando as pequenas coisas', image: 'assets/img/album/34.jpg', flipped: false },
    { subtitle: 'Desafio', description: 'Um abraço apertado', image: 'assets/img/album/35.jpg', flipped: false },
    { subtitle: 'Descoberta', description: 'Celebração de amizades', image: 'assets/img/album/36.jpg', flipped: false },
    { subtitle: 'Reconhecimento', description: 'Paz e serenidade', image: 'assets/img/album/38.jpg', flipped: false },
    { subtitle: 'Confiança', description: 'Reconhecimento de esforços', image: 'assets/img/album/39.jpg', flipped: false },
    { subtitle: 'Criatividade', description: 'Aventuras compartilhadas', image: 'assets/img/album/40.jpg', flipped: false },
    { subtitle: 'Sonhos', description: 'Descobrindo o mundo', image: 'assets/img/album/41.jpg', flipped: false },
    { subtitle: 'Paixão', description: 'Histórias que inspiram', image: 'assets/img/album/42.jpg', flipped: false },
    { subtitle: 'Superação', description: 'Reflexões profundas', image: 'assets/img/album/43.jpg', flipped: false },
    { subtitle: 'Esperança', description: 'Sentimentos de gratidão', image: 'assets/img/album/44.jpg', flipped: false },
    { subtitle: 'Realização', description: 'Memórias que fazem sorrir', image: 'assets/img/album/45.jpg', flipped: false },
    { subtitle: 'História', description: 'Sentimentos de felicidade', image: 'assets/img/album/46.jpg', flipped: false },
    { subtitle: 'Sentimento', description: 'Apreciando a jornada', image: 'assets/img/album/47.jpg', flipped: false },
    { subtitle: 'Carinho', description: 'Momentos de introspecção', image: 'assets/img/album/48.jpg', flipped: false },
    { subtitle: 'Abraço', description: 'Alegria e celebração', image: 'assets/img/album/49.jpg', flipped: false },
    { subtitle: 'Família', description: 'Confiança e apoio', image: 'assets/img/album/50.jpg', flipped: false },
    { subtitle: 'Momentos Especiais', description: 'Momentos de carinho', image: 'assets/img/album/51.jpg', flipped: false },
    { subtitle: 'Segurança', description: 'Apreciando cada instante', image: 'assets/img/album/52.jpg', flipped: false },
    { subtitle: 'Desempenho', description: 'Um sentimento de realização', image: 'assets/img/album/53.jpg', flipped: false },
    { subtitle: 'Relaxamento', description: 'Sentimentos profundos', image: 'assets/img/album/54.jpg', flipped: false },
    { subtitle: 'Nostalgia', description: 'Um momento inesquecível', image: 'assets/img/album/55.jpg', flipped: false },
    { subtitle: 'Sentimento', description: 'Recordações especiais', image: 'assets/img/album/56.jpg', flipped: false },
    { subtitle: 'Alegria', description: 'Uma alegria contagiante', image: 'assets/img/album/57.jpg', flipped: false },
    { subtitle: 'Ternura', description: 'Celebrando a vida', image: 'assets/img/album/58.jpg', flipped: false },
    { subtitle: 'Reflexão', description: 'Um dia para lembrar', image: 'assets/img/album/59.jpg', flipped: false },
    { subtitle: 'Celebração', description: 'Experiência única', image: 'assets/img/album/60.jpg', flipped: false },
    { subtitle: 'Memórias', description: 'Sorrisos compartilhados', image: 'assets/img/album/61.jpg', flipped: false },
    { subtitle: 'Felicidade', description: 'Sentimentos profundos', image: 'assets/img/album/62.jpg', flipped: false },
    { subtitle: 'Orgulho', description: 'Histórias contadas', image: 'assets/img/album/63.jpg', flipped: false },
    { subtitle: 'Amor', description: 'Memórias eternas', image: 'assets/img/album/64.jpg', flipped: false },
    { subtitle: 'Apreciar', description: 'Um dia perfeito', image: 'assets/img/album/65.jpg', flipped: false },
    { subtitle: 'Saúde', description: 'Uma lembrança querida', image: 'assets/img/album/66.jpg', flipped: false },
    { subtitle: 'Sentimento', description: 'Paz interior', image: 'assets/img/album/67.jpg', flipped: false },
    { subtitle: 'Homenagem', description: 'Momentos felizes', image: 'assets/img/album/68.jpg', flipped: false },
    { subtitle: 'Encanto', description: 'Conexões verdadeiras', image: 'assets/img/album/69.jpg', flipped: false },
    { subtitle: 'Confiança', description: 'A magia do momento', image: 'assets/img/album/70.jpg', flipped: false },
    { subtitle: 'Festejo', description: 'Uma nova aventura', image: 'assets/img/album/71.jpg', flipped: false },
    { subtitle: 'Segurança', description: 'Celebração de conquistas', image: 'assets/img/album/72.jpg', flipped: false },
    { subtitle: 'Comemoração', description: 'Gratidão e alegria', image: 'assets/img/album/73.jpg', flipped: false },
    { subtitle: 'Aventura', description: 'Um sonho realizado', image: 'assets/img/album/74.jpg', flipped: false },
    { subtitle: 'Sonho', description: 'Beleza e harmonia', image: 'assets/img/album/75.jpg', flipped: false },
    { subtitle: 'História', description: 'Reflexões sobre a vida', image: 'assets/img/album/76.jpg', flipped: false },
    { subtitle: 'Compreensão', description: 'Momentos de calma', image: 'assets/img/album/77.jpg', flipped: false },
    { subtitle: 'Sentimento', description: 'Carinho e afeto', image: 'assets/img/album/78.jpg', flipped: false },
    { subtitle: 'Amizade', description: 'Um sorriso genuíno', image: 'assets/img/album/79.jpg', flipped: false },
    { subtitle: 'Gratidão', description: 'Lembranças que aquecem o coração', image: 'assets/img/album/80.jpg', flipped: false },
    { subtitle: 'Inspiração', description: 'Felicidade pura', image: 'assets/img/album/81.jpg', flipped: false },
    { subtitle: 'Riso', description: 'Superando desafios', image: 'assets/img/album/82.jpg', flipped: false },
    { subtitle: 'Luz', description: 'Emoções intensas', image: 'assets/img/album/83.jpg', flipped: false },
    { subtitle: 'Harmonia', description: 'Momentos de reflexão', image: 'assets/img/album/84.jpg', flipped: false },
    { subtitle: 'Encanto', description: 'Conquista pessoal', image: 'assets/img/album/85.jpg', flipped: false },
    { subtitle: 'Magia', description: 'Alegria em cada detalhe', image: 'assets/img/album/86.jpg', flipped: false },
    { subtitle: 'Calma', description: 'Sentimento de realização', image: 'assets/img/album/87.jpg', flipped: false },
    { subtitle: 'Orgulho', description: 'Apreciando as pequenas coisas', image: 'assets/img/album/88.jpg', flipped: false },
    { subtitle: 'Beleza', description: 'Paz e serenidade', image: 'assets/img/album/92.jpg', flipped: false }
  ];


  toggleFlip(memory: any) {
    memory.flipped = !memory.flipped;
  }
}
